exclude:
  - node_modules
  - script

sass:
  style: :compressed

#theme: jekyll-theme-notion

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/xdanger/jekyll-theme-notion"

title: 이태경 Lee taegyeong
description: 이태경입니다.
