# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: 이태경
tagline: "software engineer"
description: "fail fast, fail often"
url: https://hanarotg.github.io
baseurl: /

author:
  name: "TaeGyeong Lee"
  url: https://hanarotg.github.io

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/poole/hyde

plugins:
  - jekyll-paginate
