site: Taegyeong Lee
url: https://hanarotg.github.io/
title: Taegyeong Lee
description: Personal blog.
author:
  name: Taegyeong Lee
  email: hanarotg@naver.com
permalink: pretty

baseurl: ""

markdown: kramdown

exclude:
  - .jekyll-cache

tag_archive:
  type: liquid
  path: /tags/
  # https://github.com/jekyll/jekyll-archives
  jekyll-archives:
    enabled:
      - tags
    layouts:
      tag: tag
    permalinks:
      tag: /tag/:name/

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

gems:
  - jekyll-seo-tag
